further documentation refactoring
ewels/MegaQC pull request #197
Opened 2020-11-27 09:46 UTC by Zethson

Time to fix the remaining minor documentation issues.

I've refactored the troubleshooting page out of development section.
Maybe it is better to have one in development and one in usage? 
I feel like the production setup instructions are a little bit outdated. 
I, for one, like to work with Docker anyways.

Signed-off-by: Zethson <lukas.heumos@posteo.net>

2020-11-28 00:48 UTC, TMiguelT requested changes
* What's up with the `.inc` file extension. Are they not `.rst` files?
* Didn't we establish that `psycopq2-binary` is not recommended for production?

2020-11-28 00:48 UTC, TMiguelT commented on docs/source/docs/installation/installation_prod.inc
> +need to set the ``MEGAQC_PRODUCTION`` environment variable to true (=1).
I would still advise giving an example here. It's not intuitive how to represent a boolean via env vars

2020-11-28 00:48 UTC, TMiguelT commented on docs/source/docs/installation/installation_prod.inc
> +.. _deployment_folder: https://github.com/ewels/MegaQC/blob/master/deployment
Add final newline.

2020-11-28 00:48 UTC, TMiguelT commented on docs/source/docs/installation/installation_prod.inc
> +4. Install the JavaScript and start compiling
The way we've designed it, you shouldn't have to have compile the JS or even node installed for the production build. If you `pip install megaqc` it should contain the pre-compiled JS. If this is not the case then that's a bug, but nonetheless this section shouldn't be needed in the docs. See #106 for context.

2020-11-28 09:34 UTC, Zethson commented on docs/source/docs/installation/installation_dev.inc
> +   git clone https://github.com/ewels/MegaQC
The https:// clone URLs are available on all repositories, regardless of visibility. https:// clone URLs work even if you are behind a firewall or proxy.

```
zeth@master /tmp> git clone git@github.com:ewels/MegaQC.git                                                                                                                            (base) 
Cloning into 'MegaQC'...
Warning: Permanently added the RSA host key for IP address '140.82.121.3' to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

2020-11-28 09:49 UTC, Zethson commented
@TMiguelT The renaming of the *.rst files, which are included into other *.rst files was to prevent duplicate label warnings.
See: https://stackoverflow.com/questions/16262163/sphinxs-include-directive-and-duplicate-label-warnings

> Didn't we establish that psycopq2-binary is not recommended for production?
Yes. Did I change anything in the docs about that? I can't find it. setup.py also looks fine?

2020-11-30 13:21 UTC, TMiguelT commented
Right. I'm not a huge fan of the `.inc` because having the wrong file extension breaks a lot of tooling (e.g. the github previews, diffs, and also my editor settings).

The `psycopg` comment was in relation to this: https://github.com/ewels/MegaQC/blob/82f9f7900649d3cc238cb286b7bec4ec9c59af34/docs/source/docs/installation/installation_prod.inc#L61

2020-11-30 13:26 UTC, Zethson commented
@TMiguelT I removed the line that you pointed it.

I am also not a fan of the "wrong" file extension, but it may be the best solution.

We could either
* use *.rst, ignore the warnings and hope for the best
* don't include files but write everything into one big file
* use *.inc and lose editor support

I went for solution 3 and consider it the best of bad solutions.

Do you have other ideas?

2020-11-30 13:55 UTC, TMiguelT commented
What are your thoughts on the `include_patterns` suggestion mentioned in the link you posted?

2020-11-30 14:06 UTC, Zethson commented
Works, but then we'll have to write every include file into the patterns:

```
exclude_patterns = ["_build",
                    "Thumbs.db",
                    ".DS_Store",
                    "docs/installation/installation_dev.rst",
                    "docs/installation/installation_docker.rst",
                    "docs/installation/installation_prod.rst",
                    "docs/installation/migrations.rst"]
```

If you prefer this solution I can implement it.

2020-11-30 14:10 UTC, TMiguelT commented
I do think that's my preference, because we gain a lot of tooling, plus it becomes easier to understand the codebase (I was confused as to what type of file this was). If someone adds a new include and forgets to update the `exclude_patterns` then all that will happen is a warning, right? That seems fine. Just chuck in a comment to the `conf.py` that explains why we are doing that.

2020-11-30 14:12 UTC, Zethson commented
It may just be a warning, but it as well break a label if someone forgets it.
But a code review here should raise alarm bells when new files are included and they're labeled in various places.

2020-11-30 14:16 UTC, Zethson commented
@TMiguelT done.

2020-11-30 14:20 UTC, TMiguelT approved these changes

2020-11-30 14:21 UTC, merged