More intuitive environment variable handling
ewels/MegaQC pull request #200
Opened 2020-11-27 11:06 UTC by Zethson

Hi,

fixes #170 .

```
export FLASK_DEBUG=0                                                                                                           
export MEGAQC_PRODUCTION=1                                                                                                  

>>> from environs import Env
>>> env = Env()
>>> env.read_env()
>>> print(env.bool("FLASK_DEBUG", False))
False
>>> print(env.bool("MEGAQC_PRODUCTION", False))
True
```

Signed-off-by: Zethson <lukas.heumos@posteo.net>

2020-11-27 14:04 UTC, TMiguelT requested changes
You will also need to look into `environs`-ifying other uses of `os.environ`, for consistent behaviour:
* `megaqc/wsgi.py`
* `megaqc/settings.py`
* `megaqc/utils/settings.py`

Also, the docs will need to explain somewhere about the `.env` file.

2020-11-27 14:04 UTC, TMiguelT commented on megaqc/cli.py
> +    elif env.bool("MEGAQC_PRODUCTION", False):
Missing the `not`

2020-11-27 15:25 UTC, Zethson commented
@TMiguelT Thanks for the review.

I've added consistent env reading to the other files and hope that I didn't miss any.
Tested it briefly and it seems to do what it is supposed to do.

Honestly don't think that we need the `.env` file reading here and therefore I removed it.

2020-11-28 00:22 UTC, TMiguelT approved these changes

2020-11-28 00:22 UTC, TMiguelT commented on megaqc/settings.py
> +            env.str("DB_HOST", "localhost"), env.str("DB_PORT", "5432")
Should the port be an `int` in order to get a better error message?

2020-11-28 09:32 UTC, merged